# dinner_guests = ['Nikola Tesla', 'George Washington', 'Genghis Khan']
# print (f'{dinner_guests[0]}, will you come to dinner?')
# print (f'{dinner_guests[1]}, will you come to dinner?')
# print (f'{dinner_guests[2]}, will you come to dinner?')
# print (f'{dinner_guests[0]} can\'t make it.')
# del dinner_guests[0]
# dinner_guests.insert(0, 'Ludakris')
# print (f'{dinner_guests[0]}, will you come to dinner?')
# print (f'{dinner_guests[1]}, will you come to dinner?')
# print (f'{dinner_guests[2]}, will you come to dinner?')
# print ('Hooray, we found a bigger dinner table. Now we can invite three more people!')
# dinner_guests.insert(0, 'Elon Musk')
# dinner_guests.insert(2, 'New Zealand PM')
# dinner_guests.append('MJK')
# print (f'{dinner_guests[0]}, will you come to dinner?')
# print (f'{dinner_guests[1]}, will you come to dinner?')
# print (f'{dinner_guests[2]}, will you come to dinner?')
# print (f'{dinner_guests[3]}, will you come to dinner?')
# print (f'{dinner_guests[4]}, will you come to dinner?')
# print (f'{dinner_guests[5]}, will you come to dinner?')
# print ('Awww, we can only invite two people to dinner.')
# print (f'Sorry, {dinner_guests.pop(1)}, there\'s not enough room.')
# print (f'Sorry, {dinner_guests.pop(1)}, there\'s not enough room.')
# print (f'Sorry, {dinner_guests.pop(1)}, there\'s not enough room.')
# print (f'Sorry, {dinner_guests.pop(1)}, there\'s not enough room.')
# print (f'It\'s ok, {dinner_guests[0]}, there\'s enough room for you!')
# print (f'It\'s ok, {dinner_guests[1]}, there\'s enough room for you!')
# print (f"I'm inviting {len(dinner_guests)} guests to dinner!")
# del dinner_guests[0]
# del dinner_guests[0]
# print (dinner_guests)
# locations = ['Mt. Everest', 'Ireland', 'Sweden', 'Hawaii', 'Germany']
# print (locations)
# print (sorted(locations))
# print (locations)
# print (sorted(locations, reverse=True))
# print (locations)
# locations.reverse()
# print (locations)
# locations.reverse()
# print (locations)
# locations.sort()
# print (locations)
# locations.sort (reverse=True)
# print (locations)